config/routes.rb
Pixyourlife::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :photos
  root 'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user  
  default_scope -> { order('created_at DESC') }
  validates :content, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true
end

app/models/photo.rb
require "open-uri"

class Photo < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image,
  :styles => { :medium => "x300", :thumb => "x100" },
  :default_url => "www.google.fr",
  :storage => :s3,
  :s3_host_name => 's3-eu-west-1.amazonaws.com',
  :bucket => 'pyloriruc',
  :s3_credentials => S3_CREDENTIALS
    
 private
def image_url_provided?
!self.image_url.blank?
end
def download_remote_image
io = open(URI.parse(image_url))
self.original_filename = io.base_uri.path.split('/').last
self.image = io
self.image_remote_url = image_url
rescue # catch url errors with validations instead of exceptions (Errno::ENOENT, OpenURI::HTTPError, etc...)
end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
  has_many :photos, dependent: :destroy
  before_save { self.email =email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
  
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def feed
    # This is preliminary. See "Following users" for the full implementation.
    Micropost.where("user_id = ?", id)
    Photo.where("user_id = ?", id)

  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy
  
  

  def create
    @micropost = current_user.microposts.build(micropost_params)
    @photo = @micropost.build_photo
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost.destroy
    redirect_to root_url
  end
  
  private

  def micropost_params
    params.require(:micropost).permit(:content, photo_attributes: [image:  
                [:image_file_name, :image_content_type, :image_file_size, :image_update_at]])
  end

  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_url if @micropost.nil?
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy, :index, :display]
  before_action :set_photo, only: [:show, :display, :edit, :update, :destroy]

  def index
    @photos = Photo.all
  end

  def show
    @URL = String.new
  end

  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @photo }
      else
        format.html { redirect_to 'new'}
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  private
    def set_photo
      @photo = Photo.find(params[:id])
    end

    def photo_params
      params.require(:photo).permit(:image, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
    flash.now[:error] = 'Invalid email/password combination' 
    render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @feed_items = Photo.paginate(page: params[:page])
    end
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  
  def new
    @user = User.new
  end
  
  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @photo = current_user.photos.create
    @feed_items = @user.feed.paginate(page: params[:page])
  end

  def create
    @user = User.new(user_params)
    if @user.save
	  sign_in @user
      flash[:success] = "Welcome to the PYL!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end


  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def signed_in_user
      store_location
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "PYL - pix your life"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end
  
  def signed_in?
    !current_user.nil?
  end
    
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end
  
  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
   Developped by Akash-Roy Rucktooa and Oriane Blot
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://pixyourlife.blogspot.se/">Blog</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <ul class="nav pull-left">
        <%= link_to image_tag("logoseul.png", alt: "logo") %>
        </ul>
        <%= link_to "PYL *", root_path, id: "logo" %>
        
        <ul class="nav pull-right">
          <% if signed_in? %>
            <li><%= link_to "Gallery", root_path %></li>
            <li><%= link_to "Private darkroom", current_user %></li>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Edit profile", edit_user_path(current_user) %></li>
                <li><%= link_to "Help", help_path %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= full_title(yield(:title)) %></title>
	<%= stylesheet_link_tag "application", media: "all",
	"data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<% flash.each do |key, value| %>
	<div class="alert alert-<%= key %>"><%= value %></div>
	<% end %>
	<div class="container">
		<%= yield %>
		<%= render 'layouts/footer' %>
		<div>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</div>
</body>
</html>

app/views/microposts/_micropost.html.erb
<li>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
  <% if current_user?(micropost.user) %>
    <%= link_to "delete", micropost, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: micropost.content %>
  <% end %>
</li>

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/display.html.erb
<h1>display</h1>

<% if @photo.image? %>
	<div class="row">
	<aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
    </aside>
    <aside class="span8">
      <section>
        <%= image_tag @photo.image.url%>
        <span class="timestamp">
        Posted <%= time_ago_in_words(@photo.created_at) %> ago.
    </span>
      </section>
    </aside>
</div>
 <% end %>





 <!-- Button trigger modal -->
<button class="btn" data-toggle="modal" data-target="#myModal">
  <%= image_tag @photo.image.url%>
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        Je veux montrer ma photo.
      <div class="row">
	<aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
    </aside>
    <aside class="span8">
      <section>
        <%= image_tag @photo.image.url%>
        <span class="timestamp">
        Posted <%= time_ago_in_words(@photo.created_at) %> ago.
    </span>
      </section>
    </aside>
</div>


      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


 <br \><br \><br \><br \><br \><br \><br \><br \><br \><br \>
 <br \><br \><br \><br \><br \><br \><br \><br \><br \><br \>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>
    <h1> Je viens de faire un upload ! </h1>
blablablabal
<% if @photo.image? %>

<!-- Load widget code -->
<script type="text/javascript" src="http://feather.aviary.com/js/feather.js"></script>


<!-- Instantiate the widget -->
<script type="text/javascript">

    var featherEditor = new Aviary.Feather({
        apiKey: '  f20374413e3ff5a8',
        apiVersion: 2,
        theme: 'light',
        tools: 'all',
        appendTo: '',
        onSave: function(imageID, newURL) {
            var img = document.getElementById(imageID);
            img.src = newURL;
        },
        postUrl: 'http://example.com/featherposturl'
    });

    function launchEditor(id, src) {
        featherEditor.launch({
            image: id,
            url: src
        });
        return false;
    }

</script>                         

<!-- Add an edit button, passing the HTML id of the image and the public URL to the image -->
<a href="#" onclick="return launchEditor('image1', 
    '<%= @photo.image.url %>');">Edit!</a>

<img id='image1' src='<%= @photo.image.url %>' height="352" width="470"/>

<!-- original line of HTML here: -->
<img id="editableimage1" src="http://images.aviary.com/imagesv5/feather_default.jpg"/>

 
<% end %>

    <%= form_for(@photo) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :content %>
      <%= f.text_field :content %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
New photo

<%= form_for @photo, :html => { :multipart => true } do |f| %>
<%= f.file_field :image %>
<%= f.submit %>
<% end %>

app/views/photos/show.html.erb
<div class="row-fluid">

  <div class="span4">
    <br \><br \><h5>My private darkroom</h5><h2> - express your art</h2>
    <ol>
      <li>Edit your picture</li>
      <li>Give it a comment</li>
      <li>Share it</li>
      <li>Go back to the gallery to show your art</li>
    </ol>
    <br \><br \><br \>
    <%= link_to "Private darkroom", user_path , class: "btn" %>
    <%= link_to "Home gallery", root_path , class: "btn" %>
  </div>


  <div class="span8">
    <% if @photo.image? %>

<!-- Load widget code -->
<script language="JavaScript" type="text/javascript" src="https://dme0ih8comzn4.cloudfront.net/js/feather.js"></script>


<!-- Instantiate the widget -->
<script type="text/javascript">

  var featherEditor = new Aviary.Feather({
  apiKey: '  f20374413e3ff5a8',
  apiVersion: 2,
  theme: 'light',
  tools: 'all',
  appendTo: '',
  onSave: function(imageID, newURL) {
    var img = document.getElementById(imageID);
    img.src = newURL;
  },
        // postUrl: 'http://example.com/featherposturl' 
      });

function launchEditor(id, src) {
  featherEditor.launch({
    image: id,
    url: src
  });
  return false;
}

</script>                         

<!-- Add an edit button, passing the HTML id of the image and the public URL to the image -->
<a href="#"  onclick="return launchEditor('editimage1', 
'<%= @photo.image.url %>');">Edit!</a>

<img id='editimage1' src='<%= @photo.image.url %>' height="352" width="470"/>

<!-- Add an edit button, passing the HTML id of the image and the public URL of the image 
  <p><input type='image' src='http://images.aviary.com/images/edit-photo.png' value='Edit photo' onclick="return launchEditor('image1', '<%= @photo.image.url %>');" /></p> -->


  <% end %>


  <%= form_for(@photo) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :content %>
  <%= f.text_field :content %>


  <%= f.submit "Share my picture", class: "btn btn-large btn-primary" %>
  <% end %>


</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
    

    <%= render partial: 'shared/feed_item', collection: @feed_items %>
 

  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<span class="photo">
	<% if feed_item.image? %>

	<!-- Button trigger modal -->
	<a data-toggle="modal" data-target="#myModal<%= feed_item.id %>" data-refresh="true">
		<%= image_tag feed_item.image.url,:size => "200x200" %>
	</a>

	<!-- Modal -->
	<div class="modal fade" id="myModal<%= feed_item.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display:none">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-body">
					<div class="row">
						<aside>							
							<section>
								<br \>
								<% @user = User.find(feed_item.user_id) %>					
								<%= link_to gravatar_for(@user, size: 52), @user %>
								<h1>
									<%= @user.name %>
								</h1>
								<span>
									<% if current_user?(@user) %>
									  <%= link_to "view my profile", @user %>
									<% else %>
									  <%= link_to "view profile", @user %>
									<% end %>
								</span>
								<span>
									<%= pluralize(@user.photos.count, "photo") %>
								</span>
								<span class="timestamp">
									Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
									<% if current_user?(feed_item.user) %>
									<%= link_to "edit", photo_path(feed_item.id)%> /
									<%= link_to "delete", feed_item, method: :delete,
									data: { confirm: "You sure?" }%>
									<% end %>
								</span>								
							</section>
						</aside>
						<aside class="center">
							<h2> <%= feed_item.content %></h2>
							<section>	

								<%= image_tag feed_item.image.url, size: "300x300" %>								
							</section>
						</aside>
					</div>
				</div>
				<div class="modal-footer">
					<!-- bouton facebook -->
					<iframe src="//www.facebook.com/plugins/like.php?href=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;width&amp;layout=button_count&amp;action=like&amp;show_faces=false&amp;share=false&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:21px;" href= "https://pixyourlife.herokuapp.com/" allowTransparency="true"></iframe>
					<!-- bouton twitter -->
					<a href="http://twitter.com/share" class="twitter-share-button" data-url="https://pixyourlife.herokuapp.com/" data-text="I love this website" data-count="horizontal" data-lang="fr">Tweet</a>
					<script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
					<!-- bouton google+ -->
					<script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>
					<g:plusone></g:plusone>
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				</div>
			</div>
		</div>
	</div>
	<% end %>
</span>

app/views/shared/_feed_photo.html.erb
<li>
  <%= photos.image %>
  <%= link_to user.name, user %>
</li>


<%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="photo">
    <% if feed_item.image? %>
    <%= image_tag feed_item.image.url %>
    <% end %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
  <% if current_user?(feed_item.user) %>
  <%= link_to "delete", feed_item, method: :delete,
  data: { confirm: "You sure?" }%>
  <% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<div class="field">
	<%= f.text_area :content, placeholder: "Compose new micropost..." %>

</div>
<%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_other_user_info.html.erb
<%= link_to gravatar_for(@user, size: 52), @user %>
<h1>
  <%= @user.name %>
</h1>
<span>
  <%= link_to "view profile", @user %>
</span>
<span>
  <%= pluralize(@user.photos.count, "photo") %>
</span>

app/views/shared/_photo_form.html.erb
<%= form_for @photo, :html => { :multipart => true } do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<div class="field">
	 Upload a photo: <%= f.file_field :image %>

  ...or provide a URL: <%= f.text_field :image_url %>
</div>
<%= f.submit "Upload picture", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 52), current_user %>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.photos.count, "photo") %>
</span>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<br \> <br \> 
<div class="row-fluid">
<div class="row-fluid">
	<div class="span3">
	<h5>About <br \> Us</h5>
</div>
<div class="span8">
<br \> <p> We are two students from INSA of Lyon <em>(France)</em>. We are currently exchange students at the University of Technology of Lulea <em>(Sweden)</em>. As part of our course of web design, we have chosen to create PYL.</p>
</div>
</div>
<div class="row-fluid">
<div class="span8">
<br \> <p> Akash est le roi du ciel. Il est née on ne sait pas quand, on ne sait pas où, mais il est née, c'est ce qui compte.</p>
</div>
<div class="span3">
	<h5>Akash</h5>
	<%= image_tag("akash.jpg", :size => "180x180") %>
</div>
</div>
<div class="row-fluid">
<div class="span3">
	<h5>Oriane</h5>
	<%= image_tag("oriane.jpg", :size => "180x180") %>
</div>
<div class="span8">
<br \> <p> Oriane est la reine des neiges mais elle à un tempérament de feu. Gare à celui qui critique son carousel !</p>
</div>
</div>





</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<br \> <br \> 
<div class="row-fluid">
  <div class="row-fluid">
    <div class="span3">
	  <br \> <br \>
	  <h5>Contact</h5>
    </div>
    <div class="span8">
	<br \><br \><br \> <p>
	akaruc-3@student.ltu.se<br \>
	oriblo-3@student.ltu.se</p>
    </div>
  </div>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<br \> <br \> 
<div class="row-fluid">
  <div class="row-fluid">
    <div class="span3">
	  <br \> <br \>
	  <h5>Help</h5>
    </div>
    <div class="span8">
	<br \> <p>You're lost in the PYL world ? Do not worry here some advise to start easily to impress the world with your art ...<br \><br \>

	Create an account<br \>
	Upload your pictures<br \>
	Modify them with aviary (click on edit on the left of the picture after your upload)<br \>
	Share them with the PYL community !<br \>

</p>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<% if signed_in? %>
<% provide(:title, 'Home gallery') %>
<br \>

<div class="row-fluid">

    <div class="span4">
    <br/>
      <h7>Enjoy the PYL* experience ! <br \> Go in your private darkroom :<br \></h7><br/><br/>
      Upload pictures from your computer<br \>
        <i class="icon-pencil "></i> Modify them <br \>
        <i class="icon-globe "></i> Share them with our community </h2>
      </div>
      <div class="span6">
      <br \><br \><h5>PYL*</h5><h2> - common gallery</h2>
      </div>
      </div>
<hr>
    <br \><br \>

    <div class="row-fluid">
    <div class="span12">
      <%= render 'shared/feed' %>
    </div>
    </div>
  

<% else %>

  
  
  <div class="center hero-unit">
    <div class="row-fluid">
    <div class="span7"><h3>Welcome on PYL*</h3></div>
    <div class="span5">
    <div id="myCarousel" class="carousel slide">
        <div class="carousel-inner">
        <div class="active item">
        <%= link_to image_tag("pylslide1.jpg", alt: "takepicture", width: "600", height:"300") %>
        </div>
          <div class="item">
            <%= link_to image_tag("pylslide2.jpg", alt: "modifyit", width: "600", height:"300") %>
          </div>
        </div>
        <!-- Carousel nav -->
        <a class="carousel-control left" href="#myCarousel" data-slide="prev" data-refresh="true">&lsaquo;</a>
        <a class="carousel-control right" href="#myCarousel" data-slide="next" data-refresh="true">&rsaquo;</a>
      
   </div>
  </div>  
</div>
    
    <h4>
      Are you ready to pix your life ?
    </h4>
    <%= link_to "Sign up now!", signup_path , class: "btn btn-large btn-primary" %>
    <br \><br \>
    
    <%= link_to image_tag("pixyourlife.jpg", alt: "Pix your life") %>
     
  
  </div>
 
    
    

   


  <% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
</li>